apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-controller
spec:
  replicas: 1
  selector:
    app: kafka
    name: kafka
  template:
    metadata:
      labels:
        app: kafka
        name: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-service
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-svc:2181
